### 회원가입

POST http://localhost:8080/auth/signup
Content-Type: application/json

{
  "name": "백인수",
  "email": "saymay10@naver.com",
  "password": "1234"

}

### 로그인

#POST http://localhost:8080/auth/login
#Content-Type: application/json
#
#{
#  "email": "hodolman88@gmail.com",
#  "password": "1234"
#}

POST http://localhost:8080/auth/login
Content-Type: application/x-www-form-urlencoded
# 폼으로 해당 경로로 POST 요청을 Spring에서 알아서 전달한다.

username=saymay10@naver.com&password=1234&remember=1

### 메인 페이지

GET http://localhost:8080

### 사용자 페이지

GET http://localhost:8080/user

### 관리자 페이지

GET http://localhost:8080/admin